"""HTML-рендер diff-отчёта bench. ponytail: rung 4 — stdlib only, single-EXE safe."""
from __future__ import annotations

from html import escape
from pathlib import Path
from typing import Optional

from .bench import diff_report


def _fmt(value: object) -> str:
    """Форматировать значение для HTML: число → 2 знака, dict/список → кратко."""
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.2f}"
    if isinstance(value, dict):
        items = ", ".join(f"{escape(k)}: {_fmt(v)}" for k, v in value.items())
        return "{" + items + "}"
    if isinstance(value, list):
        return "[" + ", ".join(_fmt(v) for v in value) + "]"
    return escape(str(value))


def _delta_cell(delta: float) -> str:
    """CSS-класс и стрелка для дельты: + зелёный/плохой, − зелёный/хороший (зависит от метрики)."""
    if delta == 0:
        return '<td class="zero">0</td>'
    css = "good" if delta < 0 else "bad"
    return f'<td class="{css}">{delta:+.2f}</td>'


def render_html_diff(a, b) -> str:
    """Вернуть HTML-страницу с diff-отчётом. ponytail: rung 4 — single-EXE, stdlib."""
    report = diff_report(a, b)
    rows = []
    for metric, vals in report["deltas"].items():
        rows.append(
            f"<tr><td>{escape(metric)}</td>"
            f"<td>{_fmt(vals['before'])}</td>"
            f"<td>{_fmt(vals['after'])}</td>"
            f"{_delta_cell(vals['delta'])}</tr>"
        )
    metrics_table = "\n".join(rows) if rows else "<tr><td colspan=4>no data</td></tr>"

    # services_by_state — особый случай: dict, не число
    svc_a = report["before"].get("services_by_state", {})
    svc_b = report["after"].get("services_by_state", {})
    svc_rows = []
    all_states = sorted(set(svc_a) | set(svc_b))
    for state in all_states:
        va = svc_a.get(state, 0)
        vb = svc_b.get(state, 0)
        svc_rows.append(
            f"<tr><td>{escape(state)}</td><td>{va}</td><td>{vb}</td>"
            f"{_delta_cell(vb - va)}</tr>"
        )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>win11opt bench diff — {escape(report['generated_at'])}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, sans-serif; margin: 32px; max-width: 900px; }}
  h1 {{ color: #007acc; }}
  h2 {{ margin-top: 28px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 8px 0 16px; }}
  th, td {{ padding: 6px 12px; border: 1px solid #ddd; text-align: left; }}
  th {{ background: #f5f5f5; }}
  td.good {{ color: #2e7d32; font-weight: bold; }}
  td.bad {{ color: #c62828; font-weight: bold; }}
  td.zero {{ color: #888; }}
  .meta {{ color: #888; font-size: 0.9em; }}
  footer {{ margin-top: 32px; color: #888; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>win11opt bench diff report</h1>
<p class="meta">Generated: {escape(report['generated_at'])}</p>

<h2>System metrics</h2>
<table>
  <tr><th>Metric</th><th>Before</th><th>After</th><th>Δ</th></tr>
  {metrics_table}
</table>

<h2>Services by state</h2>
<table>
  <tr><th>State</th><th>Before</th><th>After</th><th>Δ</th></tr>
  {''.join(svc_rows) if svc_rows else '<tr><td colspan=4>no data</td></tr>'}
</table>

<footer>
  Generated by win11opt <code>bench diff --html</code>. Privacy-first: no network calls.
</footer>
</body>
</html>
"""


def save_html_diff(a, b, path: Optional[Path] = None) -> Path:
    """Сохранить HTML-отчёт. Если path не указан — _bench_dir()/diff-<ts>.html."""
    from .bench import _bench_dir
    from datetime import datetime
    if path is None:
        ts = datetime.now().strftime("%Y%m%d-%H%M%S")
        path = _bench_dir() / f"diff-{ts}.html"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_html_diff(a, b), encoding="utf-8")
    return path
